export type Subsystem = "power" | "hvac" | "fire" | "crew" | "water";
export type Status = "normal" | "warning" | "critical";

export type Room = {
  id: string;
  name: string;
  grid: string;
  /** percentage rect on the blueprint image */
  x: number;
  y: number;
  w: number;
  h: number;
  subsystems: Subsystem[];
  level: 1 | 2 | 3;
  baseTemp: number;
  baseOccupancy: number;
  basePower: number;
  status: Status;
};

export const BHARATI_ROOMS: Room[] = [
  // --- FAR LEFT BALCONY / WALKWAY ---
  {
    id: "balcony-walkway",
    name: "Balcony / Walkway (West)",
    grid: "Grid 1 (External)",
    x: 6.5,
    y: 16.0,
    w: 4.2,
    h: 73.5,
    subsystems: ["crew", "fire"],
    level: 2,
    baseTemp: -25.2,
    baseOccupancy: 0,
    basePower: 0.1,
    status: "normal",
  },

  // --- TOP ROW (NORTH SIDE: Grid 1 to 21) ---
  {
    id: "conference",
    name: "Conference Room",
    grid: "Grid 1–3",
    x: 11.2,
    y: 16.0,
    w: 8.2,
    h: 14.5,
    subsystems: ["hvac", "crew", "fire"],
    level: 2,
    baseTemp: 21.4,
    baseOccupancy: 6,
    basePower: 2.4,
    status: "normal",
  },
  {
    id: "meeting",
    name: "Meeting Room",
    grid: "Grid 3–5",
    x: 19.6,
    y: 16.0,
    w: 7.6,
    h: 14.5,
    subsystems: ["hvac", "crew"],
    level: 2,
    baseTemp: 21.0,
    baseOccupancy: 3,
    basePower: 1.6,
    status: "normal",
  },
  {
    id: "room-1",
    name: "Room 1 (Residential)",
    grid: "Grid 5–6",
    x: 27.4,
    y: 16.0,
    w: 5.2,
    h: 14.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.5,
    baseOccupancy: 2,
    basePower: 0.9,
    status: "normal",
  },
  {
    id: "room-2",
    name: "Room 2 (Residential)",
    grid: "Grid 6–7",
    x: 32.8,
    y: 16.0,
    w: 5.2,
    h: 14.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.8,
    baseOccupancy: 1,
    basePower: 0.8,
    status: "normal",
  },
  {
    id: "room-3",
    name: "Room 3 (Residential)",
    grid: "Grid 7–8",
    x: 38.2,
    y: 16.0,
    w: 5.2,
    h: 14.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.2,
    baseOccupancy: 1,
    basePower: 0.85,
    status: "normal",
  },
  {
    id: "room-4",
    name: "Room 4 (Residential)",
    grid: "Grid 8–9",
    x: 43.6,
    y: 16.0,
    w: 4.1,
    h: 14.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.6,
    baseOccupancy: 1,
    basePower: 0.8,
    status: "normal",
  },
  {
    id: "room-5",
    name: "Room 5 (Residential)",
    grid: "Grid 9–10",
    x: 47.9,
    y: 16.0,
    w: 4.1,
    h: 14.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.0,
    baseOccupancy: 1,
    basePower: 0.82,
    status: "normal",
  },
  {
    id: "room-6",
    name: "Room 6 (Residential)",
    grid: "Grid 10–11",
    x: 52.2,
    y: 16.0,
    w: 4.1,
    h: 14.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.4,
    baseOccupancy: 1,
    basePower: 0.78,
    status: "normal",
  },
  {
    id: "room-7",
    name: "Room 7 (Residential)",
    grid: "Grid 11–12",
    x: 56.5,
    y: 16.0,
    w: 4.1,
    h: 14.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.9,
    baseOccupancy: 1,
    basePower: 0.81,
    status: "normal",
  },
  {
    id: "room-8",
    name: "Room 8 (Residential)",
    grid: "Grid 12–13",
    x: 60.8,
    y: 16.0,
    w: 4.1,
    h: 14.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.5,
    baseOccupancy: 2,
    basePower: 0.95,
    status: "normal",
  },
  {
    id: "room-9",
    name: "Room 9 (Residential)",
    grid: "Grid 13–14",
    x: 65.1,
    y: 16.0,
    w: 4.1,
    h: 14.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.7,
    baseOccupancy: 1,
    basePower: 0.8,
    status: "normal",
  },
  {
    id: "room-10",
    name: "Room 10 (Residential)",
    grid: "Grid 14–15",
    x: 69.4,
    y: 16.0,
    w: 4.1,
    h: 14.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.1,
    baseOccupancy: 1,
    basePower: 0.83,
    status: "normal",
  },
  {
    id: "room-11",
    name: "Room 11 (Residential)",
    grid: "Grid 15–16",
    x: 73.7,
    y: 16.0,
    w: 4.1,
    h: 14.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.8,
    baseOccupancy: 1,
    basePower: 0.8,
    status: "normal",
  },
  {
    id: "room-12",
    name: "Room 12 (Residential)",
    grid: "Grid 16–17",
    x: 78.0,
    y: 16.0,
    w: 4.1,
    h: 14.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.3,
    baseOccupancy: 1,
    basePower: 0.77,
    status: "normal",
  },
  {
    id: "room-13",
    name: "Room 13 (Residential)",
    grid: "Grid 17–18",
    x: 82.3,
    y: 16.0,
    w: 4.1,
    h: 14.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.4,
    baseOccupancy: 2,
    basePower: 0.92,
    status: "normal",
  },
  {
    id: "room-13b",
    name: "Room 13B (Residential)",
    grid: "Grid 18–19",
    x: 86.6,
    y: 16.0,
    w: 4.1,
    h: 14.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.6,
    baseOccupancy: 1,
    basePower: 0.8,
    status: "normal",
  },
  {
    id: "room-13c",
    name: "Room 13C (Residential)",
    grid: "Grid 19–20",
    x: 90.9,
    y: 16.0,
    w: 4.1,
    h: 14.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.9,
    baseOccupancy: 1,
    basePower: 0.82,
    status: "normal",
  },

  // --- MIDDLE SECTION (UTILITIES, SOCIAL & SERVICES) ---
  {
    id: "support-service",
    name: "Support Service Office",
    grid: "Grid 9–11",
    x: 43.6,
    y: 33.5,
    w: 11.2,
    h: 6.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.2,
    baseOccupancy: 1,
    basePower: 1.2,
    status: "normal",
  },
  {
    id: "electrical",
    name: "Electrical / HVAC Room",
    grid: "Grid 12–13",
    x: 55.4,
    y: 33.5,
    w: 6.6,
    h: 6.5,
    subsystems: ["power", "hvac", "fire"],
    level: 2,
    baseTemp: 31.6,
    baseOccupancy: 0,
    basePower: 28.4,
    status: "critical",
  },
  {
    id: "linen-wood",
    name: "Linen & Wood Store",
    grid: "Grid 14–15",
    x: 66.8,
    y: 33.5,
    w: 5.0,
    h: 6.5,
    subsystems: ["fire"],
    level: 2,
    baseTemp: 18.5,
    baseOccupancy: 0,
    basePower: 0.3,
    status: "normal",
  },
  {
    id: "dining",
    name: "Dining Hall",
    grid: "Grid 1–4",
    x: 11.2,
    y: 37.5,
    w: 12.2,
    h: 30.0,
    subsystems: ["hvac", "crew", "fire", "power"],
    level: 2,
    baseTemp: 22.1,
    baseOccupancy: 14,
    basePower: 5.6,
    status: "normal",
  },
  {
    id: "kitchen",
    name: "Kitchen",
    grid: "Grid 4–6",
    x: 23.8,
    y: 37.5,
    w: 6.2,
    h: 15.0,
    subsystems: ["power", "fire", "water", "hvac"],
    level: 2,
    baseTemp: 24.8,
    baseOccupancy: 3,
    basePower: 12.4,
    status: "warning",
  },
  {
    id: "pantry",
    name: "Pantry",
    grid: "Grid 6–7",
    x: 30.2,
    y: 37.5,
    w: 4.4,
    h: 15.0,
    subsystems: ["power", "fire"],
    level: 2,
    baseTemp: 21.0,
    baseOccupancy: 1,
    basePower: 2.1,
    status: "normal",
  },
  {
    id: "laundry",
    name: "Laundry",
    grid: "Grid 4–5",
    x: 23.8,
    y: 52.8,
    w: 5.2,
    h: 14.8,
    subsystems: ["water", "power"],
    level: 2,
    baseTemp: 26.2,
    baseOccupancy: 1,
    basePower: 6.8,
    status: "normal",
  },
  {
    id: "utility",
    name: "Utility Room",
    grid: "Grid 5–7",
    x: 29.2,
    y: 52.8,
    w: 5.4,
    h: 14.8,
    subsystems: ["water", "power", "hvac"],
    level: 2,
    baseTemp: 22.5,
    baseOccupancy: 0,
    basePower: 3.4,
    status: "normal",
  },
  {
    id: "staircase",
    name: "Staircase & Elevator Core",
    grid: "Grid 7–9",
    x: 34.9,
    y: 37.5,
    w: 8.4,
    h: 30.0,
    subsystems: ["fire", "crew"],
    level: 2,
    baseTemp: 18.2,
    baseOccupancy: 0,
    basePower: 0.4,
    status: "normal",
  },
  {
    id: "toilet-m",
    name: "Toilet (Men)",
    grid: "Grid 9–10",
    x: 43.6,
    y: 52.8,
    w: 4.4,
    h: 14.8,
    subsystems: ["water", "hvac"],
    level: 2,
    baseTemp: 20.4,
    baseOccupancy: 1,
    basePower: 1.1,
    status: "normal",
  },
  {
    id: "toilet-w",
    name: "Toilet (Women)",
    grid: "Grid 10–11",
    x: 48.2,
    y: 52.8,
    w: 4.4,
    h: 14.8,
    subsystems: ["water", "hvac"],
    level: 2,
    baseTemp: 20.6,
    baseOccupancy: 1,
    basePower: 1.1,
    status: "normal",
  },
  {
    id: "toilet-p",
    name: "Toilet (Personnel)",
    grid: "Grid 11–12",
    x: 52.8,
    y: 52.8,
    w: 4.4,
    h: 14.8,
    subsystems: ["water", "hvac"],
    level: 2,
    baseTemp: 20.2,
    baseOccupancy: 0,
    basePower: 0.9,
    status: "normal",
  },
  {
    id: "multipurpose",
    name: "Multipurpose Hall",
    grid: "Grid 13–17",
    x: 60.5,
    y: 39.5,
    w: 11.5,
    h: 28.0,
    subsystems: ["hvac", "crew", "fire", "power"],
    level: 2,
    baseTemp: 21.8,
    baseOccupancy: 9,
    basePower: 7.4,
    status: "normal",
  },
  {
    id: "linen-storage",
    name: "Linen Storage",
    grid: "Grid 16–17",
    x: 72.2,
    y: 39.5,
    w: 3.6,
    h: 5.5,
    subsystems: ["fire"],
    level: 2,
    baseTemp: 17.8,
    baseOccupancy: 0,
    basePower: 0.2,
    status: "normal",
  },
  {
    id: "recreation",
    name: "Recreation Room",
    grid: "Grid 17–19",
    x: 76.2,
    y: 37.5,
    w: 7.4,
    h: 30.0,
    subsystems: ["crew", "hvac"],
    level: 2,
    baseTemp: 22.6,
    baseOccupancy: 5,
    basePower: 3.1,
    status: "normal",
  },
  {
    id: "workspace",
    name: "Common Workspace",
    grid: "Grid 19–21",
    x: 84.0,
    y: 37.5,
    w: 11.5,
    h: 30.0,
    subsystems: ["crew", "hvac", "power"],
    level: 2,
    baseTemp: 21.2,
    baseOccupancy: 8,
    basePower: 4.9,
    status: "normal",
  },

  // --- BOTTOM ROW (SOUTH SIDE: Grid 1 to 21) ---
  {
    id: "lounge",
    name: "Lounge",
    grid: "Grid 1–3",
    x: 11.2,
    y: 76.0,
    w: 8.2,
    h: 13.5,
    subsystems: ["crew", "hvac"],
    level: 2,
    baseTemp: 22.4,
    baseOccupancy: 4,
    basePower: 2.1,
    status: "normal",
  },
  {
    id: "room-14",
    name: "Room 14",
    grid: "Grid 3–4",
    x: 19.6,
    y: 76.0,
    w: 4.1,
    h: 13.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.8,
    baseOccupancy: 1,
    basePower: 0.8,
    status: "normal",
  },
  {
    id: "room-15",
    name: "Room 15",
    grid: "Grid 4–5",
    x: 23.9,
    y: 76.0,
    w: 4.1,
    h: 13.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.1,
    baseOccupancy: 1,
    basePower: 0.82,
    status: "normal",
  },
  {
    id: "room-16",
    name: "Room 16",
    grid: "Grid 5–6",
    x: 28.2,
    y: 76.0,
    w: 4.1,
    h: 13.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.5,
    baseOccupancy: 1,
    basePower: 0.78,
    status: "warning",
  },
  {
    id: "room-20",
    name: "Room 20 (Double Suite)",
    grid: "Grid 7–9",
    x: 34.9,
    y: 76.0,
    w: 8.4,
    h: 13.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.5,
    baseOccupancy: 2,
    basePower: 1.4,
    status: "normal",
  },
  {
    id: "room-23",
    name: "Room 23 (Double Suite)",
    grid: "Grid 9–11",
    x: 43.6,
    y: 76.0,
    w: 8.5,
    h: 13.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.0,
    baseOccupancy: 2,
    basePower: 1.35,
    status: "normal",
  },
  {
    id: "room-18",
    name: "Room 18",
    grid: "Grid 11–12",
    x: 52.3,
    y: 76.0,
    w: 4.1,
    h: 13.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.9,
    baseOccupancy: 1,
    basePower: 0.8,
    status: "normal",
  },
  {
    id: "room-28a",
    name: "Room 28",
    grid: "Grid 12–13",
    x: 56.6,
    y: 76.0,
    w: 4.1,
    h: 13.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.7,
    baseOccupancy: 1,
    basePower: 0.79,
    status: "normal",
  },
  {
    id: "room-28b",
    name: "Room 28B",
    grid: "Grid 13–14",
    x: 60.9,
    y: 76.0,
    w: 4.1,
    h: 13.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.3,
    baseOccupancy: 1,
    basePower: 0.84,
    status: "normal",
  },
  {
    id: "room-28c",
    name: "Room 28C",
    grid: "Grid 14–15",
    x: 65.2,
    y: 76.0,
    w: 4.1,
    h: 13.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.4,
    baseOccupancy: 1,
    basePower: 0.77,
    status: "normal",
  },
  {
    id: "room-25a",
    name: "Room 25",
    grid: "Grid 15–16",
    x: 69.5,
    y: 76.0,
    w: 4.1,
    h: 13.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.0,
    baseOccupancy: 1,
    basePower: 0.81,
    status: "normal",
  },
  {
    id: "room-25b",
    name: "Room 25B",
    grid: "Grid 16–17",
    x: 73.8,
    y: 76.0,
    w: 4.1,
    h: 13.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.8,
    baseOccupancy: 1,
    basePower: 0.8,
    status: "normal",
  },
  {
    id: "room-25c",
    name: "Room 25C",
    grid: "Grid 17–18",
    x: 78.1,
    y: 76.0,
    w: 4.1,
    h: 13.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.2,
    baseOccupancy: 1,
    basePower: 0.83,
    status: "normal",
  },
  {
    id: "room-26",
    name: "Room 26",
    grid: "Grid 18–19",
    x: 82.4,
    y: 76.0,
    w: 4.1,
    h: 13.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.6,
    baseOccupancy: 1,
    basePower: 0.79,
    status: "normal",
  },
  {
    id: "room-27",
    name: "Room 27",
    grid: "Grid 19–21",
    x: 86.7,
    y: 76.0,
    w: 8.4,
    h: 13.5,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.1,
    baseOccupancy: 2,
    basePower: 1.3,
    status: "normal",
  },
];



export const MAITRI_ROOMS: Room[] = [
  // --- TOP ROW (NORTH WING: ROOMS 1 TO 12) ---
  {
    id: "room-1",
    name: "Room 1 (Residential)",
    grid: "Grid 1–2",
    x: 6.8,
    y: 16.5,
    w: 7.3,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.5,
    baseOccupancy: 2,
    basePower: 0.9,
    status: "normal",
  },
  {
    id: "room-2",
    name: "Room 2 (Residential)",
    grid: "Grid 2–3",
    x: 14.1,
    y: 16.5,
    w: 7.3,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.8,
    baseOccupancy: 1,
    basePower: 0.8,
    status: "normal",
  },
  {
    id: "room-3",
    name: "Room 3 (Residential)",
    grid: "Grid 3–4",
    x: 21.4,
    y: 16.5,
    w: 7.3,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.2,
    baseOccupancy: 1,
    basePower: 0.85,
    status: "normal",
  },
  {
    id: "room-4",
    name: "Room 4 (Residential)",
    grid: "Grid 4–5",
    x: 28.7,
    y: 16.5,
    w: 7.3,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.6,
    baseOccupancy: 1,
    basePower: 0.8,
    status: "normal",
  },
  {
    id: "room-5",
    name: "Room 5 (Residential)",
    grid: "Grid 5–6",
    x: 36.0,
    y: 16.5,
    w: 7.3,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.0,
    baseOccupancy: 1,
    basePower: 0.82,
    status: "normal",
  },
  {
    id: "room-6",
    name: "Room 6 (Residential)",
    grid: "Grid 6–10",
    x: 43.3,
    y: 16.5,
    w: 7.3,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.4,
    baseOccupancy: 1,
    basePower: 0.78,
    status: "normal",
  },
  {
    id: "room-7",
    name: "Room 7 (Residential)",
    grid: "Grid 10–12",
    x: 50.6,
    y: 16.5,
    w: 7.3,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.9,
    baseOccupancy: 1,
    basePower: 0.81,
    status: "normal",
  },
  {
    id: "room-8",
    name: "Room 8 (Residential)",
    grid: "Grid 12–14",
    x: 57.9,
    y: 16.5,
    w: 7.3,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.5,
    baseOccupancy: 2,
    basePower: 0.95,
    status: "normal",
  },
  {
    id: "room-9",
    name: "Room 9 (Residential)",
    grid: "Grid 14–16",
    x: 65.2,
    y: 16.5,
    w: 7.3,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.7,
    baseOccupancy: 1,
    basePower: 0.8,
    status: "normal",
  },
  {
    id: "room-10",
    name: "Room 10 (Residential)",
    grid: "Grid 16–18",
    x: 72.5,
    y: 16.5,
    w: 7.3,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.1,
    baseOccupancy: 1,
    basePower: 0.83,
    status: "normal",
  },
  {
    id: "room-11",
    name: "Room 11 (Residential)",
    grid: "Grid 18–19",
    x: 79.8,
    y: 16.5,
    w: 7.3,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.8,
    baseOccupancy: 1,
    basePower: 0.8,
    status: "normal",
  },
  {
    id: "room-12",
    name: "Room 12 (Residential)",
    grid: "Grid 19–20",
    x: 87.1,
    y: 16.5,
    w: 7.3,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.3,
    baseOccupancy: 1,
    basePower: 0.77,
    status: "normal",
  },

  // --- MIDDLE ROW (CENTRAL RESEARCH & FACILITIES) ---
  {
    id: "dining-hall",
    name: "Dining Hall",
    grid: "Grid 1–3",
    x: 6.8,
    y: 41.5,
    w: 12.0,
    h: 21.0,
    subsystems: ["hvac", "crew", "fire", "power"],
    level: 2,
    baseTemp: 22.1,
    baseOccupancy: 10,
    basePower: 4.8,
    status: "normal",
  },
  {
    id: "kitchen",
    name: "Kitchen",
    grid: "Grid 3–4",
    x: 18.9,
    y: 41.5,
    w: 8.5,
    h: 21.0,
    subsystems: ["power", "fire", "water", "hvac"],
    level: 2,
    baseTemp: 24.8,
    baseOccupancy: 3,
    basePower: 12.4,
    status: "normal",
  },
  {
    id: "pantry",
    name: "Pantry",
    grid: "Grid 4–6",
    x: 27.5,
    y: 41.5,
    w: 8.5,
    h: 21.0,
    subsystems: ["power", "fire", "hvac"],
    level: 2,
    baseTemp: 20.5,
    baseOccupancy: 1,
    basePower: 2.1,
    status: "normal",
  },
  {
    id: "staircase",
    name: "Staircase",
    grid: "Grid 6",
    x: 39.5,
    y: 41.5,
    w: 6.8,
    h: 21.0,
    subsystems: ["fire", "crew"],
    level: 2,
    baseTemp: 18.2,
    baseOccupancy: 0,
    basePower: 0.4,
    status: "normal",
  },
  {
    id: "toilets-north",
    name: "Toilets (North)",
    grid: "Grid 10",
    x: 46.5,
    y: 41.5,
    w: 4.2,
    h: 9.8,
    subsystems: ["water", "hvac"],
    level: 2,
    baseTemp: 20.4,
    baseOccupancy: 1,
    basePower: 1.1,
    status: "normal",
  },
  {
    id: "toilets-south",
    name: "Toilets (South)",
    grid: "Grid 10",
    x: 46.5,
    y: 52.7,
    w: 4.2,
    h: 9.8,
    subsystems: ["water", "hvac"],
    level: 2,
    baseTemp: 20.6,
    baseOccupancy: 1,
    basePower: 1.1,
    status: "normal",
  },
  {
    id: "meteorology-lab",
    name: "Meteorology Lab",
    grid: "Grid 10–12",
    x: 50.9,
    y: 41.5,
    w: 8.5,
    h: 21.0,
    subsystems: ["power", "hvac", "crew"],
    level: 2,
    baseTemp: 21.4,
    baseOccupancy: 2,
    basePower: 3.8,
    status: "normal",
  },
  {
    id: "geomagnetism-lab",
    name: "Geomagnetism Lab",
    grid: "Grid 12–14",
    x: 59.6,
    y: 41.5,
    w: 8.0,
    h: 21.0,
    subsystems: ["power", "hvac", "crew"],
    level: 2,
    baseTemp: 21.0,
    baseOccupancy: 2,
    basePower: 4.2,
    status: "normal",
  },
  {
    id: "satcom-room",
    name: "Satcom Room",
    grid: "Grid 14–16",
    x: 67.8,
    y: 41.5,
    w: 8.0,
    h: 21.0,
    subsystems: ["power", "hvac", "fire"],
    level: 2,
    baseTemp: 22.8,
    baseOccupancy: 1,
    basePower: 6.5,
    status: "normal",
  },
  {
    id: "medical-unit",
    name: "Medical Unit",
    grid: "Grid 16–18",
    x: 76.0,
    y: 41.5,
    w: 8.0,
    h: 21.0,
    subsystems: ["power", "hvac", "water", "crew", "fire"],
    level: 2,
    baseTemp: 23.0,
    baseOccupancy: 1,
    basePower: 3.2,
    status: "normal",
  },
  {
    id: "power-house",
    name: "Power House",
    grid: "Grid 18–20",
    x: 84.2,
    y: 41.5,
    w: 10.2,
    h: 21.0,
    subsystems: ["power", "fire", "hvac"],
    level: 2,
    baseTemp: 31.6,
    baseOccupancy: 1,
    basePower: 28.4,
    status: "warning",
  },

  // --- BOTTOM ROW (SOUTH WING: ROOMS 13 TO 22) ---
  {
    id: "room-13",
    name: "Room 13 (Residential)",
    grid: "Grid 1–2",
    x: 6.8,
    y: 68.5,
    w: 8.8,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.4,
    baseOccupancy: 2,
    basePower: 0.92,
    status: "normal",
  },
  {
    id: "room-14",
    name: "Room 14 (Residential)",
    grid: "Grid 2–3",
    x: 15.7,
    y: 68.5,
    w: 8.8,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.8,
    baseOccupancy: 1,
    basePower: 0.8,
    status: "normal",
  },
  {
    id: "room-15",
    name: "Room 15 (Residential)",
    grid: "Grid 3–4",
    x: 24.6,
    y: 68.5,
    w: 8.8,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.1,
    baseOccupancy: 1,
    basePower: 0.82,
    status: "normal",
  },
  {
    id: "room-16",
    name: "Room 16 (Residential)",
    grid: "Grid 4–5",
    x: 33.5,
    y: 68.5,
    w: 8.8,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.5,
    baseOccupancy: 1,
    basePower: 0.78,
    status: "normal",
  },
  {
    id: "room-17",
    name: "Room 17 (Residential)",
    grid: "Grid 5–6",
    x: 42.4,
    y: 68.5,
    w: 8.8,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.0,
    baseOccupancy: 1,
    basePower: 0.81,
    status: "normal",
  },
  {
    id: "room-18",
    name: "Room 18 (Residential)",
    grid: "Grid 6–10",
    x: 51.3,
    y: 68.5,
    w: 8.8,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.9,
    baseOccupancy: 1,
    basePower: 0.8,
    status: "normal",
  },
  {
    id: "room-19",
    name: "Room 19 (Residential)",
    grid: "Grid 10–12",
    x: 60.2,
    y: 68.5,
    w: 8.8,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.7,
    baseOccupancy: 1,
    basePower: 0.79,
    status: "normal",
  },
  {
    id: "room-20",
    name: "Room 20 (Residential)",
    grid: "Grid 12–14",
    x: 69.1,
    y: 68.5,
    w: 8.8,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.5,
    baseOccupancy: 2,
    basePower: 1.4,
    status: "normal",
  },
  {
    id: "room-21",
    name: "Room 21 (Residential)",
    grid: "Grid 14–16",
    x: 78.0,
    y: 68.5,
    w: 8.8,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 21.0,
    baseOccupancy: 1,
    basePower: 0.81,
    status: "normal",
  },
  {
    id: "room-22",
    name: "Room 22 (Residential)",
    grid: "Grid 16–20",
    x: 86.9,
    y: 68.5,
    w: 7.5,
    h: 19.0,
    subsystems: ["crew", "hvac", "fire"],
    level: 2,
    baseTemp: 20.6,
    baseOccupancy: 1,
    basePower: 0.79,
    status: "normal",
  },
];



export function getRoomsForStation(stationId: string): Room[] {
  return stationId === "maitri" ? MAITRI_ROOMS : BHARATI_ROOMS;
}

export const FLOOR_ROOMS = BHARATI_ROOMS;

export type SectionZone = {
  id: string;
  name: string;
  grid: string;
  x: number;
  y: number;
  w: number;
  h: number;
  level: 1 | 2 | 3;
  subsystems: Subsystem[];
  baseTemp: number;
  baseOccupancy: number;
  basePower: number;
  status: Status;
};

export const SECTION_ZONES: SectionZone[] = [
  // --- LEVEL 3 (Terrace, HVAC & Observatory Level) ---
  {
    id: "s-aircon",
    name: "Air Condition Plant",
    grid: "Grid 5–7 · Level 3",
    x: 25.2,
    y: 23.0,
    w: 9.8,
    h: 12.0,
    level: 3,
    subsystems: ["hvac", "power"],
    baseTemp: 26.3,
    baseOccupancy: 0,
    basePower: 14.2,
    status: "normal",
  },
  {
    id: "s-stair-l3",
    name: "Staircase Core (Level 3)",
    grid: "Grid 8–9 · Level 3",
    x: 35.2,
    y: 23.0,
    w: 4.6,
    h: 12.0,
    level: 3,
    subsystems: ["fire"],
    baseTemp: 17.5,
    baseOccupancy: 0,
    basePower: 0.3,
    status: "normal",
  },
  {
    id: "s-vestibule",
    name: "Vestibule",
    grid: "Grid 9–10 · Level 3",
    x: 40.0,
    y: 23.0,
    w: 4.2,
    h: 12.0,
    level: 3,
    subsystems: ["hvac", "crew"],
    baseTemp: 18.0,
    baseOccupancy: 0,
    basePower: 0.6,
    status: "normal",
  },
  {
    id: "s-terrace",
    name: "Terrace & Observatory",
    grid: "Grid 10–13 · Level 3",
    x: 44.5,
    y: 24.5,
    w: 12.0,
    h: 8.0,
    level: 3,
    subsystems: ["crew", "power"],
    baseTemp: -26.4,
    baseOccupancy: 0,
    basePower: 1.1,
    status: "normal",
  },

  // --- LEVEL 2 (Living & Command Zone) ---
  {
    id: "s-emergency-l2",
    name: "Emergency Exit (West)",
    grid: "Grid 1 · Level 2",
    x: 4.8,
    y: 37.0,
    w: 4.0,
    h: 14.0,
    level: 2,
    subsystems: ["fire"],
    baseTemp: 12.0,
    baseOccupancy: 0,
    basePower: 0.2,
    status: "normal",
  },
  {
    id: "s-dining",
    name: "Dining Hall",
    grid: "Grid 1–4 · Level 2",
    x: 9.0,
    y: 37.0,
    w: 12.0,
    h: 14.0,
    level: 2,
    subsystems: ["hvac", "crew"],
    baseTemp: 22.0,
    baseOccupancy: 12,
    basePower: 5.2,
    status: "normal",
  },
  {
    id: "s-cold-1",
    name: "Cold Storage 1",
    grid: "Grid 4–5 · Level 2",
    x: 21.4,
    y: 37.0,
    w: 4.4,
    h: 14.0,
    level: 2,
    subsystems: ["power"],
    baseTemp: -18.4,
    baseOccupancy: 0,
    basePower: 9.1,
    status: "normal",
  },
  {
    id: "s-cold-2",
    name: "Cold Storage 2",
    grid: "Grid 5–6 · Level 2",
    x: 26.0,
    y: 37.0,
    w: 4.4,
    h: 14.0,
    level: 2,
    subsystems: ["power"],
    baseTemp: -18.0,
    baseOccupancy: 0,
    basePower: 8.8,
    status: "normal",
  },
  {
    id: "s-electric",
    name: "Electric Equipment",
    grid: "Grid 7–8 · Level 2",
    x: 30.6,
    y: 37.0,
    w: 4.4,
    h: 14.0,
    level: 2,
    subsystems: ["power", "fire"],
    baseTemp: 29.7,
    baseOccupancy: 0,
    basePower: 22.6,
    status: "warning",
  },
  {
    id: "s-stair-l2",
    name: "Staircase Core (Level 2)",
    grid: "Grid 8–9 · Level 2",
    x: 35.2,
    y: 37.0,
    w: 4.6,
    h: 14.0,
    level: 2,
    subsystems: ["fire"],
    baseTemp: 18.0,
    baseOccupancy: 1,
    basePower: 0.4,
    status: "normal",
  },
  {
    id: "s-toilet",
    name: "Toilet Block",
    grid: "Grid 10–12 · Level 2",
    x: 43.0,
    y: 37.0,
    w: 8.4,
    h: 14.0,
    level: 2,
    subsystems: ["water"],
    baseTemp: 20.2,
    baseOccupancy: 1,
    basePower: 1.4,
    status: "normal",
  },
  {
    id: "s-bath",
    name: "Bathroom",
    grid: "Grid 12–13 · Level 2",
    x: 51.6,
    y: 37.0,
    w: 8.0,
    h: 14.0,
    level: 2,
    subsystems: ["water", "hvac"],
    baseTemp: 23.4,
    baseOccupancy: 2,
    basePower: 3.2,
    status: "normal",
  },
  {
    id: "s-entertainment",
    name: "Entertainment Zone",
    grid: "Grid 14–16 · Level 2",
    x: 59.8,
    y: 37.0,
    w: 12.5,
    h: 14.0,
    level: 2,
    subsystems: ["crew", "hvac"],
    baseTemp: 22.8,
    baseOccupancy: 7,
    basePower: 4.1,
    status: "normal",
  },
  {
    id: "s-corridor-l2",
    name: "Corridor (Level 2)",
    grid: "Grid 17–18 · Level 2",
    x: 72.5,
    y: 37.0,
    w: 3.8,
    h: 14.0,
    level: 2,
    subsystems: ["fire"],
    baseTemp: 19.8,
    baseOccupancy: 1,
    basePower: 0.4,
    status: "normal",
  },
  {
    id: "s-lounge",
    name: "Lounge & Bar",
    grid: "Grid 18–20 · Level 2",
    x: 76.5,
    y: 37.0,
    w: 10.8,
    h: 14.0,
    level: 2,
    subsystems: ["crew", "hvac"],
    baseTemp: 22.2,
    baseOccupancy: 6,
    basePower: 3.6,
    status: "normal",
  },
  {
    id: "s-balcony",
    name: "Balcony",
    grid: "Grid 20–21 · Level 2",
    x: 87.5,
    y: 37.0,
    w: 6.6,
    h: 14.0,
    level: 2,
    subsystems: ["crew"],
    baseTemp: -24.8,
    baseOccupancy: 0,
    basePower: 0.2,
    status: "normal",
  },

  // --- LEVEL 1 & SUB-LEVEL (Technical & Utility Zone) ---
  {
    id: "s-garage",
    name: "Garage",
    grid: "Grid 1–5 · Level 1",
    x: 9.2,
    y: 52.0,
    w: 16.5,
    h: 14.0,
    level: 1,
    subsystems: ["fire", "power"],
    baseTemp: 8.2,
    baseOccupancy: 1,
    basePower: 4.4,
    status: "normal",
  },
  {
    id: "s-boiler",
    name: "Boiler Room (Sub-Level)",
    grid: "Grid 2–3 · Sub-level 1",
    x: 10.8,
    y: 66.5,
    w: 9.4,
    h: 13.0,
    level: 1,
    subsystems: ["power", "hvac", "fire"],
    baseTemp: 42.6,
    baseOccupancy: 0,
    basePower: 31.8,
    status: "critical",
  },
  {
    id: "s-workshop",
    name: "Workshop",
    grid: "Grid 5–8 · Level 1",
    x: 26.0,
    y: 52.0,
    w: 9.0,
    h: 12.0,
    level: 1,
    subsystems: ["power", "fire"],
    baseTemp: 15.8,
    baseOccupancy: 2,
    basePower: 6.3,
    status: "normal",
  },
  {
    id: "s-stair-l1",
    name: "Staircase Core (Level 1)",
    grid: "Grid 8–9 · Level 1",
    x: 35.2,
    y: 52.0,
    w: 4.6,
    h: 12.0,
    level: 1,
    subsystems: ["fire"],
    baseTemp: 16.8,
    baseOccupancy: 0,
    basePower: 0.3,
    status: "normal",
  },
  {
    id: "s-service-passage",
    name: "Service Airlock / Passage",
    grid: "Grid 9–10 · Level 1",
    x: 40.0,
    y: 52.0,
    w: 2.8,
    h: 12.0,
    level: 1,
    subsystems: ["fire", "hvac"],
    baseTemp: 15.0,
    baseOccupancy: 0,
    basePower: 0.4,
    status: "normal",
  },
  {
    id: "s-storage",
    name: "Storage Room",
    grid: "Grid 10–12 · Level 1",
    x: 43.0,
    y: 52.0,
    w: 10.0,
    h: 12.0,
    level: 1,
    subsystems: ["fire"],
    baseTemp: 12.4,
    baseOccupancy: 0,
    basePower: 0.6,
    status: "normal",
  },
  {
    id: "s-corridor-l1",
    name: "Corridor (Level 1)",
    grid: "Grid 12–13 · Level 1",
    x: 53.2,
    y: 52.0,
    w: 5.0,
    h: 12.0,
    level: 1,
    subsystems: ["fire"],
    baseTemp: 16.5,
    baseOccupancy: 0,
    basePower: 0.3,
    status: "normal",
  },
  {
    id: "s-lab",
    name: "Laboratory · Biology",
    grid: "Grid 13–15 · Level 1",
    x: 58.4,
    y: 52.0,
    w: 8.8,
    h: 12.0,
    level: 1,
    subsystems: ["hvac", "crew", "power"],
    baseTemp: 21.1,
    baseOccupancy: 3,
    basePower: 5.8,
    status: "normal",
  },
];

export const SUBSYSTEM_LABELS: Record<Subsystem, string> = {
  power: "Power & CHP Generators",
  hvac: "HVAC & Heating",
  fire: "Fire & Safety",
  crew: "Crew Occupancy",
  water: "Water & Desalination",
};

export const CREW_NAMES = [
  "Dr. A. Iyer",
  "S. Rathore",
  "Lt. M. Bose",
  "P. Nambiar",
  "K. Deshmukh",
  "Dr. R. Tiwari",
  "J. Lakra",
  "V. Chauhan",
  "N. Pillai",
  "T. Gogoi",
];

export const STATIONS = [
  {
    id: "bharati",
    name: "Bharati Station",
    region: "Larsemann Hills",
    coords: "69°24′S 76°11′E",
    crew: 24,
  },
  {
    id: "maitri",
    name: "Maitri Station",
    region: "Schirmacher Oasis",
    coords: "70°46′S 11°44′E",
    crew: 18,
  },
] as const;
